### ISSUE TITLE
New feature "OrganizeClass", displaces comments of the class functions.

### ISSUE THREAD

**Issue by in-asif-mulla** [phpfmt/php.tools#51]
New feature "OrganizeClass", displaces comments of the class functions. When added configuration the comments/description present above the class functions moved to top of all class member variable declaration section.

**Comment by phpfmt** [comment]
@in-asif-mulla I am sorry for this inconvenience. The problem with comments is that we can never get from the context to what they are really referring to. It might be a piece of code before or a piece after. Therefore, the decision was to move the comments to the top instead of letting them commenting wrong lines after the method reordering.
